import type { Metadata } from "next";
import "../assets/globals.css";
import { Providers } from "./providers";
import { Box, Flex } from "@chakra-ui/react";
import SideBar from "../components/Home/SideBar";
import { fonts } from "../assets/fonts/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Flex
            height="100%"
            width="100%"
            background="transparent"
            justifyContent="space-between"
            position="relative"
            fontFamily={fonts.newsreader.variable}
          >
            <Box className="web-view__left-side">
              <SideBar />
            </Box>
            <Box className="web-view__right-side">
              <Box boxShadow="2xl">{children}</Box>
            </Box>
          </Flex>
        </Providers>
      </body>
    </html>
  );
}
